apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app-rollout
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: cappybara12/assignment-ai-planet:new2
          ports:
            - containerPort: 8080
  strategy:
    canary:
      steps:
        - setWeight: 20
          pause: {}
        - setWeight: 40
          pause:
            duration: 10m
        - setWeight: 60
          pause:
            duration: 5m
        - setWeight: 80
          pause:
            duration: 5m
